/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.mycompany.sticky_rice_restaurant;

/**
 *
 * @author WINDOWS
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThucDon = new javax.swing.JButton();
        btnDatBan = new javax.swing.JButton();
        btnDoanhThu = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnThongTin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sticky Rice Restaurant");
        setResizable(false);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(180, 132, 216));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 0));

        jPanel2.setBackground(new java.awt.Color(180, 132, 216));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Home Page.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel2.add(jButton1);

        jPanel4.add(jPanel2);

        btnHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bill_2.png"))); // NOI18N
        btnHoaDon.setPreferredSize(new java.awt.Dimension(100, 60));
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        jPanel4.add(btnHoaDon);

        btnThucDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThucDon.setForeground(new java.awt.Color(255, 255, 255));
        btnThucDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Restaurant Menu_2.png"))); // NOI18N
        btnThucDon.setPreferredSize(new java.awt.Dimension(100, 60));
        btnThucDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucDonActionPerformed(evt);
            }
        });
        jPanel4.add(btnThucDon);

        btnDatBan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDatBan.setForeground(new java.awt.Color(255, 255, 255));
        btnDatBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Table.png"))); // NOI18N
        btnDatBan.setPreferredSize(new java.awt.Dimension(100, 60));
        btnDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatBanActionPerformed(evt);
            }
        });
        jPanel4.add(btnDatBan);

        btnDoanhThu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        btnDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Get Revenue.png"))); // NOI18N
        btnDoanhThu.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel4.add(btnDoanhThu);

        btnNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User_1.png"))); // NOI18N
        btnNhanVien.setPreferredSize(new java.awt.Dimension(100, 60));
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jPanel4.add(btnNhanVien);

        btnThongTin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnThongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Information.png"))); // NOI18N
        btnThongTin.setPreferredSize(new java.awt.Dimension(100, 60));
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });
        jPanel4.add(btnThongTin);

        jPanel1.setBackground(new java.awt.Color(180, 132, 216));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 110));

        btnDangXuat.setBackground(new java.awt.Color(255, 51, 51));
        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Emergency Exit.png"))); // NOI18N
        btnDangXuat.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel1.add(btnDangXuat);

        jPanel4.add(jPanel1);

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menuLOGO.jpg"))); // NOI18N
        jPanel5.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        BillFrameForm BillForm = new  BillFrameForm();
        BillForm.setVisible(true);

        // Đóng JFrame "LoginUser" nếu bạn muốn
        dispose();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnThucDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucDonActionPerformed
        // TODO add your handling code here:
        ThuDonFame thuDonForm = new ThuDonFame();
        thuDonForm.setVisible(true);

        // Đóng JFrame "LoginUser" nếu bạn muốn
        dispose();
    }//GEN-LAST:event_btnThucDonActionPerformed

    private void btnDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatBanActionPerformed
        // TODO add your handling code here:

        BookingFrameForm bookingFrame = new BookingFrameForm();
        bookingFrame.setVisible(true);

        // Đóng JFrame "LoginUser" nếu bạn muốn
        dispose();
    }//GEN-LAST:event_btnDatBanActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:

        TTNVFame thongTin = new TTNVFame();
        thongTin.setVisible(true);

        // Đóng JFrame "LoginUser" nếu bạn muốn
        dispose();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThongTinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDatBan;
    private javax.swing.JButton btnDoanhThu;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnThucDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
